In [33]:
import numpy as np 
import pandas as pd

In [34]:
from google.colab import files

uploaded = files.upload()

Saving FoodBalanceSheets_E_Africa_NOFLAG.csv to FoodBalanceSheets_E_Africa_NOFLAG (1).csv

In [35]:
df = pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv', encoding='latin-1')
df

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
...,...,...,...,...,...,...,...,...,...,...,...,...
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [36]:
dfE = df.groupby('Element').sum()
dfE.sum()

<ipython-input-36-6bcbf1117da2>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  dfE = df.groupby('Element').sum()

Area Code       8.182547e+06
Item Code       1.637646e+08
Element Code    2.324888e+08
Y2014           7.965086e+06
Y2015           8.032340e+06
Y2016           8.112473e+06
Y2017           8.375729e+06
Y2018           8.554630e+06
dtype: float64

In [37]:
select2017Area = df[['Y2017', 'Area']]
grouped2017Area = select2017Area.groupby('Area').sum()
sorted_grouped2017Area = grouped2017Area.sort_values('Y2017')
seventh_lowest_area = sorted_grouped2017Area.index[6]
print("Area with the 7th lowest sum in 2017:", seventh_lowest_area)

Area with the 7th lowest sum in 2017: Guinea-Bissau

In [38]:
groupedE = df.groupby('Element').sum()
groupedE

<ipython-input-38-3146ffb70733>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupedE = df.groupby('Element').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

In [39]:
columns_2014 = [col for col in df.columns if col.endswith('2014')]
total_missing = df[columns_2014].isnull().sum().sum()
total_data_points = df[columns_2014].size
percentage_missing = (total_missing / total_data_points) * 100
print("Total number of missing data in 2014:", total_missing)
print("Percentage of missing data in 2014:", round(percentage_missing, 3))

Total number of missing data in 2014: 1589
Percentage of missing data in 2014: 2.607

In [40]:
grouped = df.groupby('Area')['Y2017'].sum()
area_with_highest_sum = grouped.idxmax()
print("Area with the highest sum in 2017:", area_with_highest_sum)

Area with the highest sum in 2017: Nigeria

In [41]:

df['Y2017'] = df['Y2017'].astype(float)  
mean_2017 = df['Y2017'].mean()
std_2017 = df['Y2017'].std()

mean_2017_rounded = round(mean_2017, 2)
std_2017_rounded = round(std_2017, 2)

print("Mean for 2017:", mean_2017_rounded)
print("Standard Deviation for 2017:", std_2017_rounded)

Mean for 2017: 140.92
Standard Deviation for 2017: 1671.86

In [42]:
unique_countries = df['Area'].unique()
total_unique_countries = len(unique_countries)
print("Total number of unique countries:", total_unique_countries)

Total number of unique countries: 49